title: Versedetect
description: Advanced Threat Detection & Response Engineering by Craig Glatt
url: https://tweakn74.github.io
baseurl: /versedetect

collections:
  detections:
    output: true
    permalink: /detections/:slug/

collections_dir: content

defaults:
  - scope:
      path: ""
      type: "detections"
    values:
      layout: detection
      status: preview
  - scope:
      path: ""
    values:
      layout: page

sass:
  sass_dir: assets/css
  style: compressed

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock
